export enum PRODUCT_CATEGORY {
  BRASILEIRA = "Brasileira",
  VEGANA = "Vegana",
  VEGETARIANA = "Vegetariana",
  SALADA = "Salada",
  JAPONESA = "Japonesa",
  CHINESA = "Chinesa",
  MEXICANA = "Mexicana",
  NORDESTINA = "Nordestina",
  HAMBURGUER = "Hambúrguer",
  PIZZA = "Pizza",
  MASSA = "Massa",
  ALCOOL = "Álcool",
  BEBIDA = "Bebida",
  REFRIGERANTE = "Refrigerante",
  GOURMET = "Gourmet",
  ALMOCO = "Almoço",
  ITALIANA = "Italiana",
  INDIANA = "Indiana",
  ARABE = "Árabe",
  TORTA = "Torta",
  SALGADO = "Salgado",
  DOCE = "Doce",
  GRELHADO = "Grelhado",
  SANDUICHE = "Sanduíche",
  OUTRO = "Outros",
}
